CREATE TABLE `CUSTOMER`
(
    `ID`         BIGINT(18) NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(100) NOT NULL,
    `LAST_NAME`  VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `VEHICLE`
(
    `ID`             BIGINT(18) NOT NULL AUTO_INCREMENT,
    `BRAND`          VARCHAR(100)   NOT NULL,
    `MODEL`          VARCHAR(100)   NOT NULL,
    `MODEL_YEAR`     SMALLINT(4),
    `VEHICLE_NUMBER` VARCHAR(50),
    `PRICE`          DECIMAL(18, 2) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `LEASING_CONTRACT`
(
    `CONTRACT_NUMBER` BIGINT(18) NOT NULL AUTO_INCREMENT,
    `MONTHLY_RATE`    DECIMAL(18, 2) NOT NULL,
    `CUSTOMER_ID`     BIGINT(18) NOT NULL,
    `VEHICLE_ID`      BIGINT(18) NOT NULL,
    UNIQUE INDEX `UP_CONTRACT_NUMBER_VEHICLE_ID` (`CONTRACT_NUMBER`, `VEHICLE_ID`),
    CONSTRAINT `FK_VEHICLE_VEHICLE_ID` FOREIGN KEY (`VEHICLE_ID`) REFERENCES `VEHICLE` (`ID`),
    CONSTRAINT `FK_VEHICLE_CUSTOMER_ID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`),
    PRIMARY KEY (`CONTRACT_NUMBER`)
);