version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: vehicle-leasing-mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=vehicle-leasing
      - MYSQL_ROOT_PASSWORD=Abc1def#
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  leasing-backend:
    image: com.allane/vehicle-leasing-backend:0.0.1-snapshot
    container_name: vehicle-leasing-backend
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - my-network
volumes:
  db:
    driver: local
networks:
  my-network:
    external:
      name: vehicle-leasing # docker create network vehicle-leasing first

