version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: vehicle-leasing-mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=vehicle-leasing
      - MYSQL_ROOT_PASSWORD=Abc1def#
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local